spring:
  application:
    name: got_telegram_bot
  jackson:
    property-naming-strategy: SNAKE_CASE
  banner:
    location: banner/banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: adminPool
      type: com.zaxxer.hikari.HikariDataSource
  profiles:
    include:
      - info_config
server:
  port: 8080

database:
  schema:
    users: users
    messages: messages
  tablename:
    users: users
    current_post: current_post


#   Для запуска локально в параметрах запуска явно указать параметры
#   Edit configuration -> Override parameters:
#   Параметры можно посмотреть в настройках Heroku, раздел Config Vars
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${BOT_USER_NAME}