spring:
  application:
    name: got_telegram_bot
  jackson:
    property-naming-strategy: SNAKE_CASE
  banner:
    location: banner/banner.txt
server:
  port: 8443

telegram:
  bot:
    token: 1085351467:AAET2sqvY35U96D-nImy9ZVYPP7bkD-Nczc
    username: got_board_bot