spring:
  application:
    name: got_telegram_bot
  jackson:
    property-naming-strategy: SNAKE_CASE
  banner:
    location: banner/banner.txt
server:
  port: 8443


#   Для запуска локально в параметрах запуска явно указать параметры
#   Edit configuration -> Override parameters:
#   Параметры можно посмотреть в настройках Heroku, раздел Config Vars
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${BOT_USER_NAME}