version: '3.5'
services:

  got_telegram_bot_postgres:
    image: sleepy_owl/got_telegram_bot_postgres:test
    container_name: got_telegram_bot_postgres
    build:
      context: ../
    deploy:
      resources:
        limits:
          memory: 400m
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: got_telegram_bot_postgres
    command: postgres -c max_connections=20
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5